# Generated by Django 3.2.24 on 2024-03-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memb_email',
            field=models.CharField(max_length=50),
        ),
    ]
